"""
writers.py — write SimSET .blocparams / .ringparams / .detparams files.

SimSET block coordinate system: x=radial, y=transaxial, z=axial (all in cm).
"""

from __future__ import annotations
import os
from datetime import date

import stir
from scanners import PhysicalSpec
from geometry import (
    mm_to_cm,
    crystal_boundaries,
    is_active_segment,
    block_dimensions_cm,
    axial_block_pitch_cm,
)

def _file_header(title: str, scanner_name: str) -> str:
    return (
        f"{'#' * 80}\n"
        f"#  {title} — {scanner_name} — {date.today()} (auto-generated by stir_to_simset)\n"
        f"{'#' * 80}\n\n"
    )

def _write_single_material_layer(
    f,
    inner_x: float,
    outer_x: float,
    material_index: int,
    active: bool,
) -> None:
    """Write a homogeneous (no y/z subdivisions) layer with one material element."""
    active_str = "TRUE" if active else "FALSE"
    f.write(f"NUM_ELEMENTS_IN_LIST\tblock_layer_info_list = 5\n")
    f.write(f"\tREAL\tblock_layer_inner_x\t= {inner_x:.6f}\n")
    f.write(f"\tREAL\tblock_layer_outer_x\t= {outer_x:.6f}\n")
    f.write(f"\tNUM_ELEMENTS_IN_LIST\tblock_layer_num_y_changes = 0\n")
    f.write(f"\tNUM_ELEMENTS_IN_LIST\tblock_layer_num_z_changes = 0\n")
    f.write(f"\tNUM_ELEMENTS_IN_LIST\tblock_layer_material_elements = 1\n")
    f.write(f"\t\tNUM_ELEMENTS_IN_LIST\tblock_material_info_list = 2\n")
    f.write(f"\t\t\tINT\tblock_material_index = {material_index}\n")
    f.write(f"\t\t\tBOOL\tblock_material_is_active = {active_str}\n\n")

def write_blocparams(
    path: str,
    scanner: stir.Scanner,
    phys: PhysicalSpec,
    phys_trans: int,
    phys_axial: int,
) -> None:
    dims = block_dimensions_cm(phys, phys_trans, phys_axial)
    wrap = mm_to_cm(phys.wrap_thickness_mm)
    c_t  = mm_to_cm(phys.crystal_trans_size_mm)
    c_a  = mm_to_cm(phys.crystal_axial_size_mm)

    y_changes = crystal_boundaries(phys_trans, c_t, wrap)
    z_changes = crystal_boundaries(phys_axial, c_a, wrap)

    num_y_segs   = len(y_changes) + 1
    num_z_segs   = len(z_changes) + 1
    num_elements = num_y_segs * num_z_segs

    with open(path, "w") as f:
        f.write(_file_header("Block Parameter File", scanner.get_name()))

        # Reference point at (0,0,0) = inner face centre of block
        f.write("# Reference point: inner face centre of block\n")
        f.write(f"REAL\tblock_reference_x\t= {0.0:.8f}\n")
        f.write(f"REAL\tblock_reference_y\t= {0.0:.8f}\n")
        f.write(f"REAL\tblock_reference_z\t= {0.0:.8f}\n\n")

        # Outer block bounds
        f.write("# Block outer bounds (x=radial, y=transaxial, z=axial)\n")
        f.write(f"REAL\tblock_x_minimum\t= {0.0:.8f}\n")
        f.write(f"REAL\tblock_x_maximum\t= {dims['x_total']:.8f}\n")
        f.write(f"REAL\tblock_y_minimum\t= {-dims['y_half']:.8f}\n")
        f.write(f"REAL\tblock_y_maximum\t= {dims['y_half']:.8f}\n")
        f.write(f"REAL\tblock_z_minimum\t= {-dims['z_half']:.8f}\n")
        f.write(f"REAL\tblock_z_maximum\t= {dims['z_half']:.8f}\n\n")

        f.write(f"INT\tblock_num_layers\t= 3\n\n")

        # Layer 0: front housing
        f.write("# --- Layer 0: front housing (inactive) ---\n")
        _write_single_material_layer(
            f, 0.0, dims["x_front"], phys.housing_material, active=False
        )

        # Layer 1: crystal array
        f.write("# --- Layer 1: crystal array ---\n")
        f.write(f"NUM_ELEMENTS_IN_LIST\tblock_layer_info_list = 5\n")
        f.write(f"\tREAL\tblock_layer_inner_x\t= {dims['x_front']:.6f}\n")
        f.write(f"\tREAL\tblock_layer_outer_x\t= {dims['x_back']:.6f}\n")

        f.write(f"\tNUM_ELEMENTS_IN_LIST\tblock_layer_num_y_changes = {len(y_changes)}\n")
        for yc in y_changes:
            f.write(f"\t\tREAL\tblock_layer_y_change = {yc:.6f}\n")

        f.write(f"\tNUM_ELEMENTS_IN_LIST\tblock_layer_num_z_changes = {len(z_changes)}\n")
        for zc in z_changes:
            f.write(f"\t\tREAL\tblock_layer_z_change = {zc:.6f}\n")

        f.write(f"\tNUM_ELEMENTS_IN_LIST\tblock_layer_material_elements = {num_elements}\n")
        elem = 0
        for iy in range(num_y_segs):
            for iz in range(num_z_segs):
                active = is_active_segment(iy, iz)
                mat = phys.crystal_material if active else phys.wrap_material
                f.write(f"\t\t# Material element {elem}\n")
                f.write(f"\t\tNUM_ELEMENTS_IN_LIST\tblock_material_info_list = 2\n")
                f.write(f"\t\t\tINT\tblock_material_index = {mat}\n")
                f.write(f"\t\t\tBOOL\tblock_material_is_active = {'TRUE' if active else 'FALSE'}\n")
                elem += 1

        f.write("\n")

        # Layer 2: back housing
        f.write("# --- Layer 2: back housing (inactive) ---\n")
        _write_single_material_layer(
            f, dims["x_back"], dims["x_total"], phys.housing_material, active=False
        )

    print(f"  Wrote {path}")

def write_ringparams(
    path: str,
    bloc_filename: str,
    scanner: stir.Scanner,
    phys: PhysicalSpec,
    num_trans_blocks: int,
    phys_axial: int,
) -> None:
    c_a  = mm_to_cm(phys.crystal_axial_size_mm)
    h_s  = mm_to_cm(phys.side_housing_mm)
    h_f  = mm_to_cm(phys.housing_front_mm)
    h_b  = mm_to_cm(phys.housing_back_mm)
    c_d  = mm_to_cm(phys.crystal_depth_mm)

    z_half       = phys_axial * c_a / 2.0 + h_s
    block_x_tot  = h_f + c_d + h_b
    r_inner      = mm_to_cm(scanner.get_inner_ring_radius())
    r_outer      = r_inner + block_x_tot + 0.5   # 5 mm margin outside the block

    angular_step = 360.0 / num_trans_blocks
    bloc_basename = os.path.basename(bloc_filename)

    with open(path, "w") as f:
        f.write(_file_header("Ring Parameter File", scanner.get_name()))

        f.write("# Ring bounding cylinders and axial extent\n")
        f.write(f"REAL\tring_x_inner_radius\t= {r_inner:.8f}\n")
        f.write(f"REAL\tring_x_outer_radius\t= {r_outer:.8f}\n")
        f.write(f"REAL\tring_y_inner_radius\t= {r_inner:.8f}\n")
        f.write(f"REAL\tring_y_outer_radius\t= {r_outer:.8f}\n")
        f.write(f"REAL\tring_z_minimum\t\t= {-z_half:.8f}\n")
        f.write(f"REAL\tring_z_maximum\t\t= {z_half:.8f}\n\n")

        f.write(f"NUM_ELEMENTS_IN_LIST\tring_num_blocks_in_ring = {num_trans_blocks}\n\n")

        for i in range(num_trans_blocks):
            angle = i * angular_step
            f.write(f"# Block {i:4d}  (azimuth {angle:.4f} deg)\n")
            f.write(f"NUM_ELEMENTS_IN_LIST\tring_block_description_list = 5\n")
            f.write(f"\tSTR\t ring_block_parameter_file\t\t= \"{bloc_basename}\"\n")
            f.write(f"\tREAL\tring_block_radial_position\t\t= {r_inner:.8f}\n")
            f.write(f"\tREAL\tring_block_angular_position\t\t= {angle:.8f}\n")
            f.write(f"\tREAL\tring_block_z_position\t\t\t= {0.0:.8f}\n")
            f.write(f"\tREAL\tring_block_transaxial_orientation\t= {0.0:.8f}\n\n")

    print(f"  Wrote {path}")


# ---------------------------------------------------------------------------
# .detparams
# ---------------------------------------------------------------------------

def write_detparams(
    path: str,
    ring_filename: str,
    scanner: stir.Scanner,
    phys: PhysicalSpec,
    num_axial_rings: int,
    phys_axial: int,
    do_forced_interaction: bool = False,
) -> None:
    pitch = axial_block_pitch_cm(phys, phys_axial)
    z_start = -(num_axial_rings * pitch) / 2.0 + pitch / 2.0
    ring_basename = os.path.basename(ring_filename)

    with open(path, "w") as f:
        f.write(_file_header("Block Detector Parameter File", scanner.get_name()))

        f.write("ENUM\tdetector_type = block\n\n")
        fi_str = "true" if do_forced_interaction else "false"
        f.write(f"BOOL\tdo_forced_interaction = {fi_str}\n\n")
        f.write(f"REAL\treference_energy_keV\t\t= {scanner.get_reference_energy():.1f}\n")
        energy_res = scanner.get_energy_resolution()
        if energy_res <= 0:
            # BGO default; warn the user
            import warnings
            warnings.warn(
                f"{scanner.get_name()}: STIR energy_resolution is 0 (unknown). "
                "Defaulting to 0.20 (20%) for BGO. Override PhysicalSpec if needed."
            )
            energy_res = 0.20
        f.write(f"REAL\tenergy_resolution_percentage\t= {energy_res * 100:.1f}\n\n")
        f.write("ENUM\tblocktomo_position_algorithm = snap_centroid_to_crystal_center\n\n")
        f.write(f"NUM_ELEMENTS_IN_LIST\tblocktomo_num_rings = {num_axial_rings}\n\n")

        for i in range(num_axial_rings):
            z_shift = z_start + i * pitch
            f.write(f"# Ring {i}  (axial shift {z_shift:.4f} cm)\n")
            f.write(f"NUM_ELEMENTS_IN_LIST\tblocktomo_ring_description_list = 3\n")
            f.write(f"\tSTR\tblocktomo_ring_parameter_file\t\t= \"{ring_basename}\"\n")
            f.write(f"\tREAL\tblocktomo_ring_axial_shift\t\t= {z_shift:.8f}\n")
            f.write(f"\tREAL\tblocktomo_ring_transaxial_rotation\t= 0.0\n\n")

    print(f"  Wrote {path}")
