#! /bin/sh

# Example run using block-detector parameter files auto-generated by make_det.py
# (stir_to_simset conversion).  Suitable for scanners registered in scanners.py.
# Convert STIR scanner definitions to SimSET detector parameter files by:
#  python make_det.py --scanner "ECAT HR+" --outdir ./ecat_hr_detector
# adjust location of SimSET to where you have it installed.
export SIMSET_DIR="~/simset/2.9.1"
export SIMSET_DIR="/homes/hinge/Projects/simset/2.9.2"

#All STIR utilities/scripts have to be in your path, e.g. if your
#INSTALL_PREFIX was ~/STIR-bin, you could do
#   PATH=$PATH:~/STIR-bin/bin

# generate emission image
generate_image generate_uniform_cylinder.par
# use the same size for the attenuation in this example
# above par file sets image values to 1, so line below will use water for attenuation
stir_math --including-first --times-scalar 0.096 uniform_cylinder_atten.hv my_uniform_cylinder.hv

# give the simulation a name. All output files will go into a new subdirectory of this name
SIM_NAME=sim5
# number of decays to simulate
PHOTONS=5000000
# specify names/locations of input files
EMISS_DATA=my_uniform_cylinder.hv
ATTEN_DATA=uniform_cylinder_atten.hv
templ_dir=`pwd`
TEMPLATE_PHG=${templ_dir}/template_phg.rec
TEMPLATE_BIN=${templ_dir}/template_bin.rec

# specify scanner — must be a name registered in make_det.py's scanners.py
SCANNER="ECAT HR+"
# maximum ring difference to store in conversion from SimSET to Interfile projdata
NUM_SEG=31

# Generate block-detector parameter files using make_det.py (stir_to_simset).
# Output goes into a subdirectory so the three files don't clutter the examples dir.
# Adjust the detector file directory
# NOTE: the naming convention for the three files is important, as they reference one another
DET_OUTDIR=${templ_dir}/ecat_hr_detector

TEMPLATE_DET=${DET_OUTDIR}/det.rec
TEMPLATE_BLOC=${DET_OUTDIR}/block.rec
TEMPLATE_RING=${DET_OUTDIR}/ring.rec

# export all variables
export SIM_NAME EMISS_DATA ATTEN_DATA TEMPLATE_PHG TEMPLATE_BIN TEMPLATE_DET
export TEMPLATE_BLOC TEMPLATE_RING
export PHOTONS NUM_SEG SCANNER

# set the simulation going
run_SimSET.sh
